import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// 상단 GNB 헤더 컴포넌트 참조
import Header from "@/app/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode; // 리액트 객체의 리액트 모드라는 타입을 가지고 있다고 지정
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center p-24">
          <Header />

          <div className="mt-20">{children}</div>
        </main>
      </body>
    </html>
  );
}
